// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMG051AqTxLYjc5toJj0O00Ay2NtfBi5I',
    appId: '1:135005933449:web:3bf2659a5be78209fc5b58',
    messagingSenderId: '135005933449',
    projectId: 'sentra-207fe',
    authDomain: 'sentra-207fe.firebaseapp.com',
    storageBucket: 'sentra-207fe.firebasestorage.app',
    measurementId: 'G-YRX96KW9PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPJi-M7VzooT6IVxKvAkZaLftAyRxhyc',
    appId: '1:880811064307:android:e3200b810c1719f1b33086',
    messagingSenderId: '880811064307',
    projectId: 'sentra-3e7a6',
    storageBucket: 'sentra-3e7a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQcrVFUJdOz3ReE-Ge84vHGuDCx_pJ8gE',
    appId: '1:135005933449:ios:e2eafabfaed186d3fc5b58',
    messagingSenderId: '135005933449',
    projectId: 'sentra-207fe',
    storageBucket: 'sentra-207fe.firebasestorage.app',
    androidClientId: '135005933449-lkk8or5e6406kfbqop3ha84chak7m272.apps.googleusercontent.com',
    iosClientId: '135005933449-b3rmrq6rda6p16bo3q8ro7ma05fgcmgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentraMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQcrVFUJdOz3ReE-Ge84vHGuDCx_pJ8gE',
    appId: '1:135005933449:ios:e2eafabfaed186d3fc5b58',
    messagingSenderId: '135005933449',
    projectId: 'sentra-207fe',
    storageBucket: 'sentra-207fe.firebasestorage.app',
    androidClientId: '135005933449-lkk8or5e6406kfbqop3ha84chak7m272.apps.googleusercontent.com',
    iosClientId: '135005933449-b3rmrq6rda6p16bo3q8ro7ma05fgcmgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.sentraMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMG051AqTxLYjc5toJj0O00Ay2NtfBi5I',
    appId: '1:135005933449:web:36d6e041ae47c141fc5b58',
    messagingSenderId: '135005933449',
    projectId: 'sentra-207fe',
    authDomain: 'sentra-207fe.firebaseapp.com',
    storageBucket: 'sentra-207fe.firebasestorage.app',
    measurementId: 'G-F3MY8E5KVD',
  );

}